ln -s /usr/lib/i386-linux-gnu/libplibsg.a libplibsg.a
ln -s /usr/lib/i386-linux-gnu/libplibsm.a libplibsm.a
ln -s /usr/lib/i386-linux-gnu/libplibssg.a libplibssg.a
ln -s /usr/lib/i386-linux-gnu/libplibsl.a libplibsl.a
ln -s /usr/lib/i386-linux-gnu/libplibssgaux.a libplibssgaux.a
ln -s /usr/lib/i386-linux-gnu/libplibul.a libplibul.a
ln -s /usr/lib/i386-linux-gnu/libplibpw.a libplibpw.a
ln -s /usr/lib/i386-linux-gnu/libplibfnt.a libplibfnt.a
ln -s /usr/lib/i386-linux-gnu/libplibpuaux.a libplibpuaux.a
ln -s /usr/lib/i386-linux-gnu/libplibpu.a libplibpu.a
ln -s /usr/lib/i386-linux-gnu/libplibjs.a libplibjs.a
ln -s /usr/lib/i386-linux-gnu/libplibpsl.a libplibpsl.a
ln -s /usr/lib/i386-linux-gnu/libplibnet.a libplibnet.a
