//
// Created by bfrasure on 2/1/19.
//

#ifndef PHYSICS_CRAFTEDSIMULATION_H
#define PHYSICS_CRAFTEDSIMULATION_H

enum CraftedSimulation {
    BODY_FORMATION, DISRUPT_GROUP, QUADRANT_TESTING, MULTIPLE_ORBITERS
};

#endif //PHYSICS_CRAFTEDSIMULATION_H
