ShapesLibrary.exe: CameraFunctions.obj 
	echo "Hi"

CameraFunctions.obj:
	g++ -Imgl -Iplibsg -Iplibul -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/CameraFunctions.d" -MT"src/CameraFunctions.d" -o"src/CameraFunctions.o" "../src/CameraFunctions.cpp"
