#!/usr/bin/env python3
"""Sample scenario parameters, run previews, score them, keep the good ones.

The point of this script is to turn "go make some cool shit" into something
repeatable: it samples the handful of knobs that actually change how a run
looks, runs each one as a short low-resolution preview, ranks the results from
the run reports the simulator writes, and can then re-render the winners at
full resolution from the exact same seed.

    tools/run_batch.py sample --archetype pair --runs 12
    tools/run_batch.py report batches/<batch> --contact-sheet --reel
    tools/run_batch.py render batches/<batch> --exclude pair-04 --top 3 --res 1440p

Every run leaves behind <name>.mp4 and <name>.json in the batch directory. The
json is enough to reproduce the run exactly.
"""

import argparse
import json
import math
import os
import random
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BINARY = REPO / "build" / "PhysicsSandbox"

# --------------------------------------------------------------------------
# Parameter sampling
#
# These ranges are where the interesting behaviour lives. Everything is
# dimensionless, so the same range works whatever scale the scenario runs at.
# --------------------------------------------------------------------------


def log_uniform(rng, low, high):
    return math.exp(rng.uniform(math.log(low), math.log(high)))


def sample_cluster(rng):
    magnitude = rng.choice([0.0, 0.15, 0.3, 0.45, 0.6, 0.75, 1.0])

    # The camera looks down z, so a z-spin flattens the cloud face-on and reads
    # as a circle. An in-plane axis shows the flattening. Sample both, favouring
    # the one you can actually see.
    if rng.random() < 0.7:
        spin = "%s,0,0" % magnitude
    else:
        spin = "0,0,%s" % magnitude

    return {
        "scenario.type": "cluster",
        # Below ~0.2 collapses hard; near 0.5 barely evolves.
        "scenario.virial_ratio": round(log_uniform(rng, 0.06, 0.55), 3),
        "cluster.radius": "2.0e7",
        "cluster.spin": spin,
        "cluster.dispersion": round(rng.uniform(0.05, 0.4), 2),
    }


def sample_pair(rng):
    return {
        "scenario.type": "pair",
        "scenario.virial_ratio": -1,
        "pair.separation": "%.2e" % (rng.uniform(3.0, 7.0) * 1e7),
        # 0 is a head-on smash; 0.4-0.9 is where tidal tails come from.
        "pair.impact_parameter": round(rng.uniform(0.0, 1.2), 2),
        # 1.0 is parabolic. Above that the pair may not stay bound.
        "pair.approach_speed": round(rng.uniform(0.3, 1.15), 2),
        "pair.mass_ratio": round(log_uniform(rng, 1.0, 10.0), 2),
        "pair.spin_a": round(rng.uniform(-0.6, 0.6), 2),
        "pair.spin_b": round(rng.uniform(-0.6, 0.6), 2),
        "pair.dispersion": round(rng.uniform(0.05, 0.25), 2),
    }


def sample_chaotic(rng):
    # The band each group's own temperature is drawn from. The bottom stays
    # cold enough that something always collapses promptly; the top is sampled
    # wide because that is the knob that decides whether a run is eight clumps
    # all doing the same thing, or clumps arriving into clouds that were
    # holding themselves up until then.
    coldest = log_uniform(rng, 0.01, 0.10)
    warmest = min(0.9, coldest * log_uniform(rng, 2.0, 30.0))

    return {
        "scenario.type": "chaotic",
        "scenario.virial_ratio": round(log_uniform(rng, 0.08, 0.5), 3),
        "chaotic.groups": rng.randint(3, 9),
        "chaotic.spread": "3.0e7",
        "chaotic.size_fraction": round(rng.uniform(0.1, 0.28), 3),
        "chaotic.infall": round(rng.uniform(0.2, 0.8), 2),
        "chaotic.tangential": round(rng.uniform(0.0, 0.6), 2),
        "chaotic.spin_max": round(rng.uniform(0.0, 0.6), 2),
        "chaotic.mass_spread": round(rng.uniform(1.0, 4.0), 2),
        "chaotic.thickness": round(rng.uniform(0.05, 0.5), 2),
        "chaotic.dispersion": round(rng.uniform(0.05, 0.25), 2),
        "chaotic.group_virial_min": round(coldest, 3),
        "chaotic.group_virial_max": round(warmest, 3),
    }


def sample_diamond(rng):
    return {
        "scenario.type": "diamond",
        "scenario.virial_ratio": round(log_uniform(rng, 0.08, 0.5), 3),
        "diamond.groups": rng.randint(3, 10),
        "diamond.ring_radius": "%.2e" % (rng.uniform(1.5, 4.0) * 1e7),
        "diamond.infall": round(rng.uniform(0.2, 0.8), 2),
        "diamond.swirl": round(rng.uniform(0.0, 0.6), 2),
        "diamond.spin": round(rng.uniform(0.0, 0.5), 2),
        "diamond.dispersion": round(rng.uniform(0.05, 0.25), 2),
    }


SAMPLERS = {
    "cluster": sample_cluster,
    "pair": sample_pair,
    "chaotic": sample_chaotic,
    "diamond": sample_diamond,
}


BASE_CONFIG = """# Generated by tools/run_batch.py - edit the batch script, not this file.
forceCalculationMethod=octree
parallel=true
octree_theta=0.5
maximum_runtime=150

numShapes={particles}
mass=598910
sandbox_width=5.2e6

dt=auto
frames_per_crossing={frames_per_crossing}

collision_radius_multiplier=30.0
merge_target_fraction=0.9
merge_target_seconds=120
minimum_merges_per_frame={min_merges}

velocity_damping=0.9995
boundary_strength=0.001
boundary_radius_factor=1.5
"""


def write_config(path, params, particles, frames_per_crossing, min_merges, name):
    lines = [BASE_CONFIG.format(
        particles=particles,
        frames_per_crossing=frames_per_crossing,
        min_merges=min_merges,
    )]
    lines.append("\nscenario.name=%s\n" % name)
    for key, value in params.items():
        lines.append("%s=%s\n" % (key, value))
    path.write_text("".join(lines))


# --------------------------------------------------------------------------
# Running
# --------------------------------------------------------------------------


def run_one(config, output, seed, res, max_frames, quiet=True):
    """Runs one simulation. Output goes to <video>.log so a failed encode can be
    read back - discarding it once hid an ffmpeg error for a whole batch."""
    command = [
        str(BINARY),
        "--config", str(config),
        "--out", str(output),
        "--seed", str(seed),
        "--record",
        "--res", res,
        "--max-frames", str(max_frames),
    ]

    log_path = Path(output).with_suffix(".log")
    with open(log_path, "wb") as log:
        result = subprocess.run(
            command,
            cwd=str(REPO),
            stdout=log if quiet else None,
            stderr=subprocess.STDOUT if quiet else None,
        )
    return result.returncode


def verify_video(path):
    """(ok, description). A run that simulated for an hour and wrote nothing is
    the expensive failure, so check the file is real before moving on."""
    video = Path(path)
    if not video.exists():
        return False, "no file was written"

    size = video.stat().st_size
    if size == 0:
        return False, "file is empty (0 bytes) - the encode failed"
    if size < 20_000:
        return False, "file is only %d bytes" % size

    try:
        probe = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "csv=p=0", str(video)],
            capture_output=True, text=True)
        duration = float(probe.stdout.strip())
    except (ValueError, OSError):
        return False, "ffprobe could not read it"

    if duration <= 0:
        return False, "zero duration"

    return True, "%.0fs, %.0f MB" % (duration, size / 1e6)


def report_failure(name, video, note):
    print("\n  !! %s produced no usable video: %s" % (name, note))
    log_path = Path(video).with_suffix(".log")
    if log_path.exists():
        tail = log_path.read_text(errors="replace").splitlines()[-12:]
        print("  --- last lines of %s ---" % log_path.name)
        for line in tail:
            print("  | %s" % line)
    print("")


# --------------------------------------------------------------------------
# Scoring
#
# Reads the sidecar the simulator wrote and asks four questions:
#   did it collapse, did it stay in frame, did anything build up, did it move?
# --------------------------------------------------------------------------


def clamp(value, low=0.0, high=1.0):
    return max(low, min(high, value))


def score_run(report):
    history = report.get("history") or []
    if len(history) < 3:
        return 0.0, {"reason": "too short"}

    radii = [sample["rms_radius_m"] for sample in history if sample["rms_radius_m"] > 0]
    if not radii:
        return 0.0, {"reason": "no radius history"}

    initial = radii[0]
    smallest = min(radii)
    final = radii[-1]
    largest_fraction = history[-1]["largest_mass_fraction"]

    # Did it actually fall together at some point?
    collapse = clamp(1.0 - smallest / initial)

    # Did it stay watchable, or did it spray off screen?
    expansion = final / initial
    bounded = 1.0 if expansion <= 1.5 else clamp(1.0 - (expansion - 1.5) / 2.0)

    # Did a dominant body build up? 5% of total mass in one object is plenty.
    structure = clamp(largest_fraction / 0.05)

    # Did anything happen at all, or was it a static blob?
    liveliness = clamp((max(radii) - smallest) / initial)

    score = (0.30 * collapse
             + 0.20 * bounded
             + 0.25 * structure
             + 0.15 * liveliness
             + 0.10 * (1.0 if report.get("completed") else 0.0))

    return score, {
        "collapse": round(collapse, 3),
        "bounded": round(bounded, 3),
        "structure": round(structure, 3),
        "liveliness": round(liveliness, 3),
        "expansion": round(expansion, 3),
        "largest_mass_fraction": largest_fraction,
    }


def load_reports(batch_dir):
    reports = []
    for sidecar in sorted(Path(batch_dir).glob("*.json")):
        if sidecar.name == "index.json":
            continue
        try:
            report = json.loads(sidecar.read_text())
        except json.JSONDecodeError:
            print("  ! unreadable report: %s" % sidecar.name)
            continue

        video = Path(report.get("video_path", ""))
        if not video.is_absolute():
            video = REPO / video
        size = video.stat().st_size if video.exists() else 0

        score, parts = score_run(report)
        # Catches the 0-byte and few-hundred-byte files a crashed run leaves.
        if size < 20_000:
            score, parts = 0.0, {"reason": "empty or missing video (%d bytes)" % size}

        reports.append({
            "name": sidecar.stem,
            "sidecar": str(sidecar),
            "video": str(video),
            "video_bytes": size,
            "seed": report.get("seed"),
            "scenario": report.get("scenario", {}),
            "score": round(score, 4),
            "parts": parts,
        })

    reports.sort(key=lambda entry: entry["score"], reverse=True)
    return reports


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------


def command_sample(args):
    if not BINARY.exists():
        sys.exit("Build first: make -j8")

    rng = random.Random(args.seed)

    batch_dir = Path(args.out or (REPO / "batches" /
                     ("%s_%s" % (datetime.now().strftime("%Y-%m-%d_%H%M"), args.archetype))))
    batch_dir.mkdir(parents=True, exist_ok=True)
    print("Batch directory: %s" % batch_dir)

    sampler = SAMPLERS[args.archetype]

    for index in range(args.runs):
        name = "%s-%02d" % (args.archetype, index)
        seed = rng.randrange(1, 2 ** 31)
        params = sampler(rng)

        config = batch_dir / ("%s.properties" % name)
        video = batch_dir / ("%s.mp4" % name)
        write_config(config, params, args.particles, args.frames_per_crossing,
                     args.min_merges, name)

        print("[%d/%d] %s seed=%d" % (index + 1, args.runs, name, seed))
        for key, value in params.items():
            print("      %-28s %s" % (key, value))

        code = run_one(config, video, seed, args.res, args.frames, quiet=not args.verbose)
        if code != 0:
            print("      ! exited with %s" % code)

        ok, note = verify_video(video)
        if ok:
            print("      wrote %s (%s)" % (video.name, note))
        else:
            report_failure(name, video, note)
            if not args.keep_going:
                sys.exit("Stopping: the rest of the batch would fail the same way. "
                         "Re-run with --keep-going to push on anyway.")

    write_index(batch_dir)
    print_ranking(batch_dir)
    build_contact_sheet(batch_dir)


def write_index(batch_dir):
    reports = load_reports(batch_dir)
    (Path(batch_dir) / "index.json").write_text(json.dumps(reports, indent=2))

    lines = ["# Batch: %s\n" % Path(batch_dir).name,
             "\n| rank | run | score | collapse | bounded | structure | liveliness | seed |",
             "\n|---|---|---|---|---|---|---|---|\n"]
    for rank, entry in enumerate(reports, start=1):
        parts = entry["parts"]
        lines.append("| %d | %s | %.3f | %s | %s | %s | %s | %s |\n" % (
            rank, entry["name"], entry["score"],
            parts.get("collapse", "-"), parts.get("bounded", "-"),
            parts.get("structure", "-"), parts.get("liveliness", "-"),
            entry["seed"]))
    (Path(batch_dir) / "summary.md").write_text("".join(lines))
    return reports


def print_ranking(batch_dir):
    reports = load_reports(batch_dir)
    print("\nRanked:")
    for rank, entry in enumerate(reports, start=1):
        print("  %2d. %-16s score=%.3f  %s" % (rank, entry["name"], entry["score"], entry["parts"]))
    print("\nsummary.md and index.json written to %s" % batch_dir)


def command_report(args):
    write_index(args.batch_dir)
    print_ranking(args.batch_dir)
    if args.contact_sheet:
        build_contact_sheet(Path(args.batch_dir), strip=args.strip)
    if args.reel:
        build_reel(Path(args.batch_dir))


def rewrite_particle_count(config, particles, scale_merges):
    """Re-render the same arrangement at a different resolution.

    Group masses, positions and velocities are per-group quantities, so the
    gravitational setup is unchanged and the bulk motion holds up. Two things
    do not carry over on their own:

      - each particle is lighter, so its radius shrinks as N^(-1/3) and the
        collision cross-section with it;
      - minimum_merges_per_frame is an absolute count, so the same value
        consumes a smaller fraction of a bigger population every frame.

    With --scale-merges both are compensated, which keeps the coalescing
    roughly on the same schedule as the preview.
    """
    original = config.read_text().splitlines()

    def current(key, fallback):
        for line in original:
            if line.startswith(key + "="):
                return float(line.split("=", 1)[1])
        return fallback

    previous = current("numShapes", 0) or current("cluster.count", 0)
    ratio = (particles / previous) if previous else 1.0

    merges = max(1, int(round(current("minimum_merges_per_frame", 0) * ratio)))
    multiplier = current("collision_radius_multiplier", 30.0) * (ratio ** (1.0 / 3.0))

    rewritten = []
    matched = False
    for line in original:
        if line.startswith("numShapes=") or line.startswith("cluster.count="):
            key = line.split("=", 1)[0]
            rewritten.append("%s=%d" % (key, particles))
            matched = True
        elif scale_merges and line.startswith("minimum_merges_per_frame="):
            rewritten.append("minimum_merges_per_frame=%d" % merges)
        elif scale_merges and line.startswith("collision_radius_multiplier="):
            rewritten.append("collision_radius_multiplier=%.3f" % multiplier)
        else:
            rewritten.append(line)

    if not matched:
        print("      ! --particles had nothing to change in %s" % config.name)
        return config

    if scale_merges and ratio != 1.0:
        print("      scaled x%.2f: minimum_merges_per_frame=%d collision_radius_multiplier=%.1f"
              % (ratio, merges, multiplier))

    detailed = config.with_name(config.stem + "-x%d.properties" % particles)
    detailed.write_text("\n".join(rewritten) + "\n")
    return detailed


def select_runs(reports, only, exclude, top):
    """Score picks the order; --only and --exclude let your eye have the final say."""
    chosen = [entry for entry in reports if entry["score"] > 0]

    if only:
        wanted = {name.strip() for name in only.split(",") if name.strip()}
        unknown = wanted - {entry["name"] for entry in reports}
        if unknown:
            sys.exit("No such run(s) in this batch: %s" % ", ".join(sorted(unknown)))
        # An explicit list means exactly those, scores and --top ignored.
        return [entry for entry in reports if entry["name"] in wanted]

    if exclude:
        dropped = {name.strip() for name in exclude.split(",") if name.strip()}
        unknown = dropped - {entry["name"] for entry in reports}
        if unknown:
            sys.exit("No such run(s) in this batch: %s" % ", ".join(sorted(unknown)))
        chosen = [entry for entry in chosen if entry["name"] not in dropped]

    return chosen[:top]


def command_render(args):
    reports = load_reports(args.batch_dir)
    winners = select_runs(reports, args.only, args.exclude, args.top)
    if not winners:
        sys.exit("Nothing selected to render in %s" % args.batch_dir)

    print("Rendering %d run(s) at %s, %d frames:" % (len(winners), args.res, args.frames))
    for entry in winners:
        print("  %-16s score=%.3f seed=%s" % (entry["name"], entry["score"], entry["seed"]))
    if args.dry_run:
        return

    destination = Path(args.dest) if args.dest else (REPO / "WorthyVideos")
    destination.mkdir(parents=True, exist_ok=True)

    for entry in winners:
        config = Path(entry["sidecar"]).with_suffix(".properties")

        if args.particles:
            config = rewrite_particle_count(config, args.particles, args.scale_merges)

        output = destination / ("%s-%s-full.mp4" % (Path(args.batch_dir).name, entry["name"]))
        print("Rendering %s -> %s (seed %s)" % (entry["name"], output.name, entry["seed"]))
        run_one(config, output, entry["seed"], args.res, args.frames, quiet=not args.verbose)

        ok, note = verify_video(output)
        if ok:
            print("  ok: %s" % note)
        else:
            report_failure(entry["name"], output, note)
            if not args.keep_going:
                sys.exit("Stopping before another long render is wasted. "
                         "Re-run with --keep-going to push on anyway.")


FONT = "/System/Library/Fonts/Supplemental/Arial.ttf"


def frame_count(video):
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0", "-count_frames",
         "-show_entries", "stream=nb_read_frames", "-of", "csv=p=0", str(video)],
        capture_output=True, text=True)
    try:
        return int(result.stdout.strip())
    except ValueError:
        return 0


def label_filter(text):
    """A readable caption in the top-left, or nothing if there's no font."""
    if not Path(FONT).exists():
        return ""
    escaped = text.replace(":", "\\:").replace("'", "")
    return (",drawtext=fontfile=%s:text='%s':x=10:y=10:fontsize=22:fontcolor=white"
            ":box=1:boxcolor=black@0.65:boxborderw=8" % (FONT, escaped))


def build_contact_sheet(batch_dir, strip=5):
    """A filmstrip per run, best first: enough to judge the arc, not one instant.

    A single mid-run thumbnail can't tell a collapse from a cloud that never
    moved, which is the whole question when you're deciding what to re-render.
    """
    reports = load_reports(batch_dir)
    if not reports:
        print("No runs found in %s" % batch_dir)
        return

    rows_dir = Path(batch_dir) / "rows"
    rows_dir.mkdir(exist_ok=True)
    for stale in rows_dir.glob("*.png"):
        stale.unlink()

    for rank, entry in enumerate(reports):
        video = Path(entry["video"])
        total = frame_count(video) if video.exists() else 0
        if total < strip:
            print("  skipping %s (%d frames)" % (entry["name"], total))
            continue

        # Evenly spaced through the run, avoiding the very first and last frame.
        picks = [int(total * (i + 0.5) / strip) for i in range(strip)]
        select = "+".join("eq(n\\,%d)" % pick for pick in picks)

        caption = "%d. %s  score %.2f  seed %s" % (
            rank + 1, entry["name"], entry["score"], entry["seed"])

        row = rows_dir / ("%02d-%s.png" % (rank, entry["name"]))
        subprocess.run(
            ["ffmpeg", "-y", "-loglevel", "error", "-i", str(video),
             "-vf", "select='%s',scale=320:-1,tile=%dx1%s" % (select, strip, label_filter(caption)),
             "-fps_mode", "passthrough", "-frames:v", "1", str(row)],
            check=False)

    made = sorted(rows_dir.glob("*.png"))
    if not made:
        print("No filmstrips could be built.")
        return

    sheet = Path(batch_dir) / "contact-sheet.png"
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-pattern_type", "glob",
         "-i", str(rows_dir / "*.png"),
         "-filter_complex", "tile=1x%d" % len(made), "-frames:v", "1", str(sheet)],
        check=False)
    print("\nContact sheet (%d runs, best first): %s" % (len(made), sheet))


def build_reel(batch_dir):
    """Every preview end to end in one labelled file, ranked best first."""
    reports = [entry for entry in load_reports(batch_dir) if Path(entry["video"]).exists()]
    if not reports:
        print("No videos to stitch.")
        return

    labelled_dir = Path(batch_dir) / "labelled"
    labelled_dir.mkdir(exist_ok=True)

    listing = []
    for rank, entry in enumerate(reports):
        caption = "%d. %s  score %.2f  seed %s" % (
            rank + 1, entry["name"], entry["score"], entry["seed"])
        labelled = labelled_dir / ("%02d.mp4" % rank)

        subprocess.run(
            ["ffmpeg", "-y", "-loglevel", "error", "-i", entry["video"],
             "-vf", "null%s" % label_filter(caption),
             "-c:v", "libx264", "-crf", "20", "-preset", "veryfast",
             "-pix_fmt", "yuv420p", str(labelled)],
            check=False)
        listing.append("file '%s'" % labelled.resolve())

    concat_list = labelled_dir / "list.txt"
    concat_list.write_text("\n".join(listing) + "\n")

    reel = Path(batch_dir) / "reel.mp4"
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0",
         "-i", str(concat_list), "-c", "copy", str(reel)],
        check=False)
    print("Reel (%d runs, best first): %s" % (len(reports), reel))


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    subparsers = parser.add_subparsers(dest="command", required=True)

    sample = subparsers.add_parser("sample", help="run a batch of sampled previews")
    sample.add_argument("--archetype", choices=sorted(SAMPLERS), default="chaotic")
    sample.add_argument("--runs", type=int, default=8)
    sample.add_argument("--seed", type=int, default=None,
                        help="seed for the sampler itself, so a batch is repeatable")
    sample.add_argument("--particles", type=int, default=1500,
                        help="particles per group; keep previews small")
    sample.add_argument("--frames", type=int, default=900,
                        help="frames per preview (900 = 37s of video)")
    sample.add_argument("--frames-per-crossing", type=int, default=300)
    sample.add_argument("--min-merges", type=int, default=6)
    sample.add_argument("--res", default="720p")
    sample.add_argument("--out", default=None)
    sample.add_argument("--verbose", action="store_true")
    sample.add_argument("--keep-going", action="store_true",
                             help="carry on after a run produces no usable video")
    sample.set_defaults(func=command_sample)

    report = subparsers.add_parser("report", help="re-score an existing batch")
    report.add_argument("batch_dir")
    report.add_argument("--contact-sheet", action="store_true",
                        help="filmstrip per run, ranked best first")
    report.add_argument("--strip", type=int, default=5,
                        help="frames per filmstrip row (default 5)")
    report.add_argument("--reel", action="store_true",
                        help="stitch every preview into one labelled reel.mp4")
    report.set_defaults(func=command_report)

    render = subparsers.add_parser("render", help="re-render the winners at full resolution")
    render.add_argument("batch_dir")
    render.add_argument("--top", type=int, default=3)
    render.add_argument("--only", default=None,
                        help="render exactly these runs, e.g. chaotic-03,chaotic-07 "
                             "(ignores score and --top)")
    render.add_argument("--exclude", default=None,
                        help="drop these runs before taking --top")
    render.add_argument("--dry-run", action="store_true",
                        help="print what would be rendered and stop")
    render.add_argument("--res", default="1440p")
    render.add_argument("--frames", type=int, default=2880)
    render.add_argument("--dest", default=None)
    render.add_argument("--particles", type=int, default=None,
                        help="re-render with this many particles per group instead")
    render.add_argument("--no-scale-merges", dest="scale_merges", action="store_false",
                        help="with --particles, leave the merge settings alone instead of "
                             "rescaling them to keep coalescing on the same schedule")
    render.add_argument("--verbose", action="store_true")
    render.add_argument("--keep-going", action="store_true",
                             help="carry on after a run produces no usable video")
    render.set_defaults(func=command_render)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
