//
// Created by bfrasure on 1/21/19.
//

#ifndef PHYSICS_CAMERAACTIONS_H
#define PHYSICS_CAMERAACTIONS_H

enum CameraAction {
    ROTATE_LEFT, ROTATE_RIGHT, ROTATE_UP, ROTATE_DOWN, TOGGLE_AUTOSCALING, STOP_ROTATION, END_SCENE
};

#endif //PHYSICS_CAMERAACTIONS_H
